const Country = require("../models/Country.model");
const User = require("../models/User.model");
const mongoose = require("mongoose");
const bcrypt = require("bcrypt");
const bcryptSalt = 10;
require("dotenv").config();

const countries = [
  // countries in total: 193, should be consistent with the enum in User.model.js and map.js library

  {
    cid: "AF",
    name: "Afghanistan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇫",
  },
  {
    cid: "AL",
    name: "Albania",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇱",
  },
  {
    cid: "DZ",
    name: "Algeria",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇿",
  },
  {
    cid: "AD",
    name: "Andorra",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇩",
  },
  {
    cid: "AO",
    name: "Angola",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇴",
  },
  {
    cid: "AG",
    name: "Antigua and Barbuda",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇬",
  },
  {
    cid: "AR",
    name: "Argentina",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇷",
  },
  {
    cid: "AM",
    name: "Armenia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇲",
  },
  {
    cid: "AU",
    name: "Australia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇺",
  },
  {
    cid: "AT",
    name: "Austria",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇹",
  },
  {
    cid: "AZ",
    name: "Azerbaijan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇿",
  },
  {
    cid: "BS",
    name: "Bahamas",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇸",
  },
  {
    cid: "BH",
    name: "Bahrain",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇭",
  },
  {
    cid: "BD",
    name: "Bangladesh",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇩",
  },
  {
    cid: "BB",
    name: "Barbados",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇧",
  },
  {
    cid: "BY",
    name: "Belarus",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇾",
  },
  {
    cid: "BE",
    name: "Belgium",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇪",
  },
  {
    cid: "BZ",
    name: "Belize",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇿",
  },
  {
    cid: "BJ",
    name: "Benin",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇯",
  },
  {
    cid: "BT",
    name: "Bhutan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇹",
  },
  {
    cid: "BO",
    name: "Bolivia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇴",
  },
  {
    cid: "BA",
    name: "Bosnia and Herzegovina",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇦",
  },
  {
    cid: "BW",
    name: "Botswana",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇼",
  },
  {
    cid: "BR",
    name: "Brazil",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇷",
  },
  {
    cid: "BN",
    name: "Brunei",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇳",
  },
  {
    cid: "BG",
    name: "Bulgaria",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇬",
  },
  {
    cid: "BF",
    name: "Burkina Faso",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇫",
  },
  {
    cid: "BI",
    name: "Burundi",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇧🇮",
  },
  {
    cid: "KH",
    name: "Cambodia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇭",
  },
  {
    cid: "CM",
    name: "Cameroon",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇲",
  },
  {
    cid: "CA",
    name: "Canada",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇦",
  },
  {
    cid: "CV",
    name: "Cape Verde",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇻",
  },
  {
    cid: "CF",
    name: "Central African Republic",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇫",
  },
  {
    cid: "TD",
    name: "Chad",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇩",
  },
  {
    cid: "CL",
    name: "Chile",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇱",
  },
  {
    cid: "CN",
    name: "China",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇳",
  },
  {
    cid: "CO",
    name: "Colombia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇴",
  },
  {
    cid: "KM",
    name: "Comoros",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇲",
  },
  {
    cid: "CG",
    name: "Congo (Brazzaville)",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇬",
  },
  {
    cid: "CD",
    name: "Congo",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇩",
  },
  {
    cid: "CR",
    name: "Costa Rica",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇷",
  },
  {
    cid: "CI",
    name: "Cote d'Ivoire",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇮",
  },
  {
    cid: "HR",
    name: "Croatia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇭🇷",
  },
  {
    cid: "CU",
    name: "Cuba",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇺",
  },
  {
    cid: "CY",
    name: "Cyprus",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇾",
  },
  {
    cid: "CZ",
    name: "Czech Republic",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇿",
  },
  {
    cid: "DK",
    name: "Denmark",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇰",
  },
  {
    cid: "DJ",
    name: "Djibouti",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇯",
  },
  {
    cid: "DM",
    name: "Dominica",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇲",
  },
  {
    cid: "DO",
    name: "Dominican Republic",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇴",
  },
  {
    cid: "TL",
    name: "East Timor (Timor Timur)",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇱",
  },
  {
    cid: "EC",
    name: "Ecuador",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇨",
  },
  {
    cid: "EG",
    name: "Egypt",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇬",
  },
  {
    cid: "SV",
    name: "El Salvador",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇻",
  },
  {
    cid: "GQ",
    name: "Equatorial Guinea",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇶",
  },
  {
    cid: "ER",
    name: "Eritrea",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇷",
  },
  {
    cid: "EE",
    name: "Estonia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇪",
  },
  {
    cid: "ET",
    name: "Ethiopia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇹",
  },
  {
    cid: "FJ",
    name: "Fiji",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇫🇯",
  },
  {
    cid: "FI",
    name: "Finland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇫🇮",
  },
  {
    cid: "FR",
    name: "France",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇫🇷",
  },
  {
    cid: "FG",
    name: "French Guiana",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇫🇬",
  },
  {
    cid: "GA",
    name: "Gabon",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇦",
  },
  {
    cid: "GM",
    name: "Gambia, The",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇲",
  },
  {
    cid: "GE",
    name: "Georgia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇪",
  },
  {
    cid: "DE",
    name: "Germany",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇩🇪",
  },
  {
    cid: "GH",
    name: "Ghana",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇭",
  },
  {
    cid: "GR",
    name: "Greece",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇷",
  },
  {
    cid: "GL",
    name: "Greenland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇱",
  },
  {
    cid: "GD",
    name: "Grenada",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇩",
  },
  {
    cid: "GT",
    name: "Guatemala",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇹",
  },
  {
    cid: "GN",
    name: "Guinea",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇳",
  },
  {
    cid: "GW",
    name: "Guinea-Bissau",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇼",
  },
  {
    cid: "GY",
    name: "Guyana",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇾",
  },
  {
    cid: "HT",
    name: "Haiti",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇭🇹",
  },
  {
    cid: "HN",
    name: "Honduras",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇭🇳",
  },
  {
    cid: "HU",
    name: "Hungary",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇭🇺",
  },
  {
    cid: "IS",
    name: "Iceland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇸",
  },
  {
    cid: "IN",
    name: "India",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇳",
  },
  {
    cid: "ID",
    name: "Indonesia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇩",
  },
  {
    cid: "IR",
    name: "Iran",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇷",
  },
  {
    cid: "IQ",
    name: "Iraq",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇶",
  },
  {
    cid: "IE",
    name: "Ireland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇪",
  },
  {
    cid: "IL",
    name: "Israel",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇱",
  },
  {
    cid: "IT",
    name: "Italy",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇮🇹",
  },
  {
    cid: "JM",
    name: "Jamaica",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇯🇲",
  },
  {
    cid: "JP",
    name: "Japan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇯🇵",
  },
  {
    cid: "JO",
    name: "Jordan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇯🇴",
  },
  {
    cid: "KZ",
    name: "Kazakhstan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇿",
  },
  {
    cid: "KE",
    name: "Kenya",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇪",
  },
  {
    cid: "KI",
    name: "Kiribati",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇮",
  },
  {
    cid: "KP",
    name: "Korea, North",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇵",
  },
  {
    cid: "KR",
    name: "Korea, South",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇷",
  },
  {
    cid: "XK",
    name: "Kosovo",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🏴",
  },
  {
    cid: "KW",
    name: "Kuwait",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇼",
  },
  {
    cid: "KG",
    name: "Kyrgyzstan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇬",
  },
  {
    cid: "LA",
    name: "Laos",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇦",
  },
  {
    cid: "LV",
    name: "Latvia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇻",
  },
  {
    cid: "LB",
    name: "Lebanon",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇧",
  },
  {
    cid: "LS",
    name: "Lesotho",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇸",
  },
  {
    cid: "LR",
    name: "Liberia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇷",
  },
  {
    cid: "LY",
    name: "Libya",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇾",
  },
  {
    cid: "LI",
    name: "Liechtenstein",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇮",
  },
  {
    cid: "LT",
    name: "Lithuania",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇹",
  },
  {
    cid: "LU",
    name: "Luxembourg",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇺",
  },
  {
    cid: "MK",
    name: "Macedonia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇰",
  },
  {
    cid: "MG",
    name: "Madagascar",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇬",
  },
  {
    cid: "MW",
    name: "Malawi",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇼",
  },
  {
    cid: "MY",
    name: "Malaysia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇾",
  },
  {
    cid: "MV",
    name: "Maldives",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇻",
  },
  {
    cid: "ML",
    name: "Mali",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇱",
  },
  {
    cid: "MT",
    name: "Malta",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇹",
  },
  {
    cid: "MH",
    name: "Marshall Islands",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇭",
  },
  {
    cid: "MR",
    name: "Mauritania",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇷",
  },
  {
    cid: "MU",
    name: "Mauritius",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇺",
  },
  {
    cid: "MX",
    name: "Mexico",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇽",
  },
  {
    cid: "FM",
    name: "Micronesia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇫🇲",
  },
  {
    cid: "MD",
    name: "Moldova",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇩",
  },
  {
    cid: "MC",
    name: "Monaco",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇨",
  },
  {
    cid: "MN",
    name: "Mongolia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇳",
  },
  {
    cid: "ME",
    name: "Montenegro",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇪",
  },
  {
    cid: "MA",
    name: "Morocco",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇦",
  },
  {
    cid: "MZ",
    name: "Mozambique",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇿",
  },
  {
    cid: "MM",
    name: "Myanmar",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇲🇲",
  },
  {
    cid: "NA",
    name: "Namibia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇦",
  },
  {
    cid: "NR",
    name: "Nauru",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇷",
  },
  {
    cid: "NP",
    name: "Nepal",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇵",
  },
  {
    cid: "NL",
    name: "Netherlands",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇱",
  },
  {
    cid: "NZ",
    name: "New Zealand",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇿",
  },
  {
    cid: "NI",
    name: "Nicaragua",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇮",
  },
  {
    cid: "NE",
    name: "Niger",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇪",
  },
  {
    cid: "NG",
    name: "Nigeria",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇬",
  },
  {
    cid: "NO",
    name: "Norway",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇳🇴",
  },
  {
    cid: "OM",
    name: "Oman",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇴🇲",
  },
  {
    cid: "PK",
    name: "Pakistan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇰",
  },
  {
    cid: "PW",
    name: "Palau",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇼",
  },
  {
    cid: "PS",
    name: "Palestine, State of",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇸",
  },
  {
    cid: "PA",
    name: "Panama",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇦",
  },
  {
    cid: "PG",
    name: "Papua New Guinea",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇬",
  },
  {
    cid: "PY",
    name: "Paraguay",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇾",
  },
  {
    cid: "PE",
    name: "Peru",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇪",
  },
  {
    cid: "PH",
    name: "Philippines",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇭",
  },
  {
    cid: "PL",
    name: "Poland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇱",
  },
  {
    cid: "PT",
    name: "Portugal",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇵🇹",
  },
  {
    cid: "QA",
    name: "Qatar",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇶🇦",
  },
  {
    cid: "RO",
    name: "Romania",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇷🇴",
  },
  {
    cid: "RU",
    name: "Russia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇷🇺",
  },
  {
    cid: "RW",
    name: "Rwanda",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇷🇼",
  },
  {
    cid: "KN",
    name: "Saint Kitts and Nevis",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇰🇳",
  },
  {
    cid: "LC",
    name: "Saint Lucia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇨",
  },
  {
    cid: "VC",
    name: "Saint Vincent and the Grenadines",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇻🇨",
  },
  {
    cid: "WS",
    name: "Samoa",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇼🇸",
  },
  {
    cid: "SM",
    name: "San Marino",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇲",
  },
  {
    cid: "ST",
    name: "Sao Tome and Principe",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇹",
  },
  {
    cid: "SA",
    name: "Saudi Arabia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇦",
  },
  {
    cid: "SN",
    name: "Senegal",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇳",
  },
  {
    cid: "RS",
    name: "Serbia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇷🇸",
  },
  {
    cid: "CS",
    name: "Serbia and Montenegro",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🏴",
  },
  {
    cid: "SC",
    name: "Seychelles",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇨",
  },
  {
    cid: "SL",
    name: "Sierra Leone",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇱",
  },
  {
    cid: "SG",
    name: "Singapore",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇬",
  },
  {
    cid: "SK",
    name: "Slovakia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇰",
  },
  {
    cid: "SI",
    name: "Slovenia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇮",
  },
  {
    cid: "SB",
    name: "Solomon Islands",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇧",
  },
  {
    cid: "SO",
    name: "Somalia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇴",
  },
  {
    cid: "ZA",
    name: "South Africa",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇿🇦",
  },
  {
    cid: "SS",
    name: "South Sudan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇸",
  },
  {
    cid: "ES",
    name: "Spain",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇸",
  },
  {
    cid: "LK",
    name: "Sri Lanka",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇱🇰",
  },
  {
    cid: "SD",
    name: "Sudan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇩",
  },
  {
    cid: "SR",
    name: "Suriname",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇷",
  },
  {
    cid: "SJ",
    name: "Svalbard and Jan Mayen",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇯",
  },
  {
    cid: "SZ",
    name: "Swaziland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇿",
  },
  {
    cid: "SE",
    name: "Sweden",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇪",
  },
  {
    cid: "CH",
    name: "Switzerland",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇨🇭",
  },
  {
    cid: "SY",
    name: "Syria",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇸🇾",
  },
  {
    cid: "TW",
    name: "Taiwan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇼",
  },
  {
    cid: "TJ",
    name: "Tajikistan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇯",
  },
  {
    cid: "TZ",
    name: "Tanzania",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇿",
  },
  {
    cid: "TH",
    name: "Thailand",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇭",
  },
  {
    cid: "TG",
    name: "Togo",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇬",
  },
  {
    cid: "TO",
    name: "Tonga",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇴",
  },
  {
    cid: "TT",
    name: "Trinidad and Tobago",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇹",
  },
  {
    cid: "TN",
    name: "Tunisia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇳",
  },
  {
    cid: "TR",
    name: "Turkey",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇷",
  },
  {
    cid: "TM",
    name: "Turkmenistan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇲",
  },
  {
    cid: "TV",
    name: "Tuvalu",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇹🇻",
  },
  {
    cid: "UG",
    name: "Uganda",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇺🇬",
  },
  {
    cid: "UA",
    name: "Ukraine",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇺🇦",
  },
  {
    cid: "AE",
    name: "United Arab Emirates",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇦🇪",
  },
  {
    cid: "GB",
    name: "United Kingdom",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇬🇧",
  },
  {
    cid: "US",
    name: "United States",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇺🇸",
  },
  {
    cid: "UY",
    name: "Uruguay",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇺🇾",
  },
  {
    cid: "UZ",
    name: "Uzbekistan",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇺🇿",
  },
  {
    cid: "VU",
    name: "Vanuatu",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇻🇺",
  },
  {
    cid: "VA",
    name: "Vatican City",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇻🇦",
  },
  {
    cid: "VE",
    name: "Venezuela",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇻🇪",
  },
  {
    cid: "VN",
    name: "Vietnam",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇻🇳",
  },
  {
    cid: "EH",
    name: "Western Sahara",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇪🇭",
  },
  {
    cid: "YE",
    name: "Yemen",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇾🇪",
  },
  {
    cid: "ZM",
    name: "Zambia",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇿🇲",
  },
  {
    cid: "ZW",
    name: "Zimbabwe",
    visitedTimes: 0,
    plannedTimes: 0,
    emoji: "🇿🇼",
  },
];

const users = [
  {
    username: "testAdmin",
    role: "admin",
    nationality: "Chinese",
    email: "testAdmin@ironhack.com",
    passwordHash: bcrypt.hashSync("Admin123!", bcrypt.genSaltSync(bcryptSalt)),
    visitedCountries: [
      {
        from: {
          country: "China",
          coordinates: [116.4074, 39.9042],
          // Beijing,
          // Coordinates may differ from users who visited China
          // This will depend on where they click on the map
        },
        to: {
          country: "United States",
          coordinates: [-95.7129, 37.0902],
        },
      },
      {
        from: {
          country: "United States",
          coordinates: [-95.7129, 37.0902],
        },
        to: {
          country: "Mexico",
          coordinates: [-99.1332, 19.4326],
        },
      },
    ],
    plannedCountries: [],
  },
  {
    username: "testUser",
    role: "user",
    nationality: "American",
    email: "testUser@ironhack.com",
    passwordHash: bcrypt.hashSync("User123!", bcrypt.genSaltSync(bcryptSalt)),
    visitedCountries: [
      {
        from: {
          country: "China",
          coordinates: [116.4074, 39.9042],
          // Coordinates may differ from users who visited China
          // This will depend on where they click on the map
        },
        to: {
          country: "United States",
          coordinates: [-95.7129, 37.0902],
        },
      },
      {
        from: {
          country: "United States",
          coordinates: [-95.7129, 37.0902],
        },
        to: {
          country: "Mexico",
          coordinates: [-99.1332, 19.4326],
        },
      },
    ],
    plannedCountries: [],
  },
];

const MONGO_URL =
  process.env.MONGODB_URI || "mongodb://localhost:27017/countries-tracker";

console.log(MONGO_URL);
mongoose
  .connect(MONGO_URL, { useNewUrlParser: true })
  .then((x) => {
    console.log(
      `Connected to Mongo! Database name: "${x.connections[0].name}"`
    );

    Country.create(countries)
      .then((countries) => {
        console.log(`Created ${countries.length} countries`);
        mongoose.connection.close();
      })
      .catch((err) => {
        console.log("Error creating countries: ", err);
      });

    User.create(users)
      .then((users) => {
        console.log(`Created ${users.length} users`);
        mongoose.connection.close();
      })
      .catch((err) => {
        console.log("Error creating users: ", err);
      });
  })
  .catch((err) => {
    console.error("Error connecting to mongo", err);
  });
